# Generated by Django 3.2.14 on 2022-08-02 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('url_link', models.URLField(max_length=400)),
                ('tag', models.ManyToManyField(related_name='posts', to='portfolios.Tag')),
            ],
        ),
    ]
